on: [workflow_dispatch]
jobs:
  example_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: 'echo "Version: ${{ matrix.version }} on ${{ matrix.os }}"'