on:
  workflow_call:
    inputs:
      your-name:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello ${{ inputs.your-name }}"